export const SIDDHIS_55_PLUS = [
  // Ten Mahavidyas (10)
  {
    slug: 'kali-sadhana',
    title: 'Kali Sadhana',
    sanskrit: 'काली',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'advanced',
    description: 'Fierce compassion and liberation through the Mahavidya Kali. Includes mantra, nyasa, and midnight practices.',
    duration: 45,
    benefits: ['liberation', 'dissolution of ego', 'divine fury', 'protection'],
    warnings: ['not for beginners', 'requires guru guidance', 'avoid during pregnancy'],
    bestTithi: [14, 15, 29, 30],
    season: 'Varsha',
    dosha: ['vata', 'pitta'],
    mantras: [{ text: 'ॐ क्रीं काली', phonetic: 'Om Kreem Kali' }],
  },
  {
    slug: 'tara-sadhana',
    title: 'Tara Sadhana',
    sanskrit: 'तारा',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'intermediate',
    description: 'Star-like guidance and liberation. Tara as the one who delivers from darkness.',
    duration: 30,
    benefits: ['guidance', 'protection', 'psychic abilities', 'safe travel'],
    bestTithi: [8, 14, 22, 29],
    season: 'Sharad',
  },
  {
    slug: 'sodashi-sadhana',
    title: 'Shodashi (Lalita) Sadhana',
    sanskrit: 'षोडशी',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'intermediate',
    description: 'The 16-year-old maiden Tripura Sundari. Includes yantra meditation and 16-syllable mantra.',
    duration: 50,
    benefits: ['divine beauty', 'prosperity', 'bliss', 'fulfillment'],
    bestTithi: [15],
  },
  {
    slug: 'bhuvaneswari-sadhana',
    title: 'Bhuvaneswari Sadhana',
    sanskrit: 'भुवनेश्वरी',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'intermediate',
    description: 'Queen of the three worlds. Includes heartspace meditation and cosmic mantra.',
    duration: 35,
    benefits: ['sovereignty', 'abundance', 'creative power'],
  },
  {
    slug: 'baglamukhi-sadhana',
    title: 'Baglamukhi Sadhana',
    sanskrit: 'बगलामुखी',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'advanced',
    description: 'The paralyzing Mahavidya. Stops enemies and obstacles. Requires strict ethics.',
    duration: 40,
    benefits: ['victory over enemies', 'silencing opposition', 'power', 'protection'],
    warnings: ['must have pure intention', 'not for aggression', 'requires brahmacharya'],
    bestTithi: [8],
  },
  {
    slug: 'matangi-sadhana',
    title: 'Matangi Sadhana',
    sanskrit: 'मातंगी',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'intermediate',
    description: 'The parrot Mahavidya. Grants eloquence, knowledge, and supernatural powers.',
    duration: 30,
    benefits: ['speech power', 'knowledge', 'music', 'charm'],
  },
  {
    slug: 'kamakhya-sadhana',
    title: 'Kamakhya Sadhana',
    sanskrit: 'कामाख्या',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'advanced',
    description: 'The yoni Mahavidya. Includes sacred sexuality and creative power awakening.',
    duration: 50,
    benefits: ['creative power', 'fertility', 'pleasure', 'kundalini activation'],
    warnings: ['for adults only', 'requires discretion', 'practice respectfully'],
  },
  {
    slug: 'bhairaavi-sadhana',
    title: 'Bhairavi Sadhana',
    sanskrit: 'भैरवी',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'advanced',
    description: 'The fiery Mahavidya. Cosmic power of creation and destruction.',
    duration: 45,
    benefits: ['power', 'transformation', 'liberation', 'union with Shiva'],
  },
  {
    slug: 'dhumavati-sadhana',
    title: 'Dhumavati Sadhana',
    sanskrit: 'धूमावती',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'advanced',
    description: 'The widow Mahavidya. Transcendence through renunciation and void experience.',
    duration: 40,
    benefits: ['detachment', 'wisdom', 'void realization', 'supernatural power'],
  },
  {
    slug: 'maha-lakshmi-sadhana',
    title: 'Maha Lakshmi Sadhana',
    sanskrit: 'महालक्ष्मी',
    category: 'tantra',
    subcategory: 'Mahavidya',
    difficulty: 'intermediate',
    description: 'Goddess of wealth and abundance. Supreme prosperity and grace.',
    duration: 30,
    benefits: ['abundance', 'prosperity', 'grace', 'fulfillment'],
  },

  // Pranayama Techniques (8)
  {
    slug: 'pranayama-kapalabhati',
    title: 'Kapalabhati',
    sanskrit: 'कपालभाति',
    category: 'pranayama',
    difficulty: 'beginner',
    description: 'Skull-shining breath. Forceful exhalation to clear nadis and energize.',
    duration: 10,
    benefits: ['mental clarity', 'energy', 'nadi purification', 'digestion'],
    dosha: ['vata'],
    season: 'Grishma',
  },
  {
    slug: 'pranayama-nadi-shodhana',
    title: 'Nadi Shodhana',
    sanskrit: 'नाडी शोधन',
    category: 'pranayama',
    difficulty: 'beginner',
    description: 'Channel purification through alternate nostril breathing.',
    duration: 15,
    benefits: ['balance', 'clarity', 'harmony', 'stress relief'],
  },
  {
    slug: 'pranayama-bhastrika',
    title: 'Bhastrika',
    sanskrit: 'भस्त्रिका',
    category: 'pranayama',
    difficulty: 'intermediate',
    description: 'Bellows breath. Rapid diaphragmatic breathing for kundalini activation.',
    duration: 10,
    benefits: ['energy', 'heat', 'kundalini activation', 'mental power'],
    warnings: ['avoid if pregnant', 'not for heart conditions'],
  },
  {
    slug: 'pranayama-sheetali',
    title: 'Sheetali Pranayama',
    sanskrit: 'शीतली',
    category: 'pranayama',
    difficulty: 'beginner',
    description: 'Cooling breath through the tongue. For heat and pitta imbalance.',
    duration: 10,
    benefits: ['cooling', 'pitta reduction', 'calm', 'digestion'],
    season: 'Grishma',
  },
  {
    slug: 'pranayama-ujjayi',
    title: 'Ujjayi Pranayama',
    sanskrit: 'उज्जयी',
    category: 'pranayama',
    difficulty: 'beginner',
    description: 'Victorious breath. Throat constriction creates internal heat and sound.',
    duration: 15,
    benefits: ['heat', 'focus', 'energy', 'meditation support'],
  },
  {
    slug: 'pranayama-surya-bhedana',
    title: 'Surya Bhedana',
    sanskrit: 'सूर्य भेदन',
    category: 'pranayama',
    difficulty: 'intermediate',
    description: 'Sun-piercing breath through right nostril only. Intense heating.',
    duration: 10,
    benefits: ['heat', 'kundalini', 'pitta increase', 'courage'],
    warnings: ['avoid high pitta', 'evening practice only'],
  },
  {
    slug: 'pranayama-chandra-bhedana',
    title: 'Chandra Bhedana',
    sanskrit: 'चंद्र भेदन',
    category: 'pranayama',
    difficulty: 'intermediate',
    description: 'Moon-piercing breath through left nostril. Cooling and feminine.',
    duration: 10,
    benefits: ['cooling', 'calm', 'moon energy', 'feminine power'],
  },
  {
    slug: 'pranayama-kumbhaka',
    title: 'Kumbhaka (Breath Retention)',
    sanskrit: 'कुंभक',
    category: 'breath-magic',
    difficulty: 'advanced',
    description: 'Advanced breath retention techniques from Kumbhaka-pranayama. Includes antara and bahya kumbhaka.',
    duration: 20,
    benefits: ['prana stabilization', 'mind control', 'siddhis', 'kundalini'],
    warnings: ['requires preparation', 'learn from qualified teacher'],
  },

  // Shatkarma (6 cleansing practices)
  {
    slug: 'shatkarma-neti',
    title: 'Neti - Nasal Cleansing',
    sanskrit: 'नेति',
    category: 'hatha-yoga',
    subcategory: 'Shatkarma',
    difficulty: 'beginner',
    description: 'Jala neti or sutra neti - nasal passage purification with water or string.',
    duration: 15,
    benefits: ['sinus clarity', 'psychic sight', 'energy channels clear', 'allergies relief'],
  },
  {
    slug: 'shatkarma-dhauti',
    title: 'Dhauti - Internal Cleansing',
    sanskrit: 'धौति',
    category: 'hatha-yoga',
    subcategory: 'Shatkarma',
    difficulty: 'intermediate',
    description: 'Vamana dhauti (vomiting) and other internal cleanses. Hatha Yoga Pradipika 2.24-32.',
    duration: 30,
    benefits: ['toxin removal', 'digestive power', 'energy clarity'],
    warnings: ['learn proper technique', 'avoid if weak'],
  },
  {
    slug: 'shatkarma-nauli',
    title: 'Nauli - Churning the Abdomen',
    sanskrit: 'नौली',
    category: 'hatha-yoga',
    subcategory: 'Shatkarma',
    difficulty: 'advanced',
    description: 'Abdominal muscle control and churning. Hatha Yoga Pradipika 2.33-35.',
    duration: 20,
    benefits: ['digestive fire', 'energy control', 'kundalini movement'],
    warnings: ['requires strong foundation'],
  },
  {
    slug: 'shatkarma-basti',
    title: 'Basti - Colon Cleansing',
    sanskrit: 'बस्ति',
    category: 'hatha-yoga',
    subcategory: 'Shatkarma',
    difficulty: 'intermediate',
    description: 'Jala basti (water) and sthala basti (dry). Lower abdomen purification.',
    duration: 20,
    benefits: ['colon health', 'vata balance', 'apana control'],
  },
  {
    slug: 'shatkarma-trataka',
    title: 'Trataka - Steady Gazing',
    sanskrit: 'त्राटक',
    category: 'hatha-yoga',
    subcategory: 'Shatkarma',
    difficulty: 'intermediate',
    description: 'Fixed gaze on a flame, point, or yantra. Develops concentration and inner sight.',
    duration: 10,
    benefits: ['mental clarity', 'psychic sight', 'concentration', 'eye power'],
  },
  {
    slug: 'shatkarma-kapalbhati',
    title: 'Kapalbhati - Skull Shining',
    sanskrit: 'कपालभाति',
    category: 'hatha-yoga',
    subcategory: 'Shatkarma',
    difficulty: 'beginner',
    description: 'Forceful exhalation. (Also listed as pranayama but classified here in traditional texts.)',
    duration: 10,
    benefits: ['mental clarity', 'nadi purification', 'energy'],
  },

  // Nyasa Techniques (5)
  {
    slug: 'nyasa-anga',
    title: 'Anga Nyasa - Limb Installation',
    sanskrit: 'अंग न्यास',
    category: 'tantra',
    subcategory: 'Nyasa',
    difficulty: 'intermediate',
    description: 'Installation of deity in body parts. Touch forehead, heart, navel, knees, feet with mantra.',
    duration: 15,
    benefits: ['deity integration', 'body sanctification', 'energy flow'],
    chakras: ['ajna', 'anahata', 'manipura', 'muladhara'],
  },
  {
    slug: 'nyasa-shadanga',
    title: 'Shadanga Nyasa - Six-Limb Installation',
    sanskrit: 'षडांग न्यास',
    category: 'tantra',
    subcategory: 'Nyasa',
    difficulty: 'intermediate',
    description: 'Installation across six energy centers: heart, right arm, left arm, navel, knees, feet.',
    duration: 20,
    benefits: ['full body activation', 'energy balance', 'protection'],
    chakras: ['anahata', 'manipura', 'muladhara'],
  },
  {
    slug: 'nyasa-samput',
    title: 'Samput Nyasa - Concealment Installation',
    sanskrit: 'संपुट न्यास',
    category: 'tantra',
    subcategory: 'Nyasa',
    difficulty: 'advanced',
    description: 'Advanced concealment technique. Binds energy within body for protection and power.',
    duration: 25,
    benefits: ['energy containment', 'psychic protection', 'power amplification'],
    warnings: ['requires guru guidance'],
  },
  {
    slug: 'nyasa-mudra-combination',
    title: 'Mudra Nyasa - Hand Gesture Installation',
    sanskrit: 'मुद्रा न्यास',
    category: 'tantra',
    subcategory: 'Nyasa',
    difficulty: 'intermediate',
    description: 'Installation through specific hand mudras. Cinmudra, Bhairava mudra, Yoni mudra combinations.',
    duration: 15,
    benefits: ['channel activation', 'energy sealing', 'concentration'],
    chakras: ['all'],
  },
  {
    slug: 'nyasa-chakra-meditation',
    title: 'Chakra Nyasa - Energy Center Installation',
    sanskrit: 'चक्र न्यास',
    category: 'tantra',
    subcategory: 'Nyasa',
    difficulty: 'intermediate',
    description: 'Installation of seed mantras in seven chakras with visualization of light and mantra.',
    duration: 30,
    benefits: ['chakra activation', 'kundalini preparation', 'energy balance'],
    chakras: ['all seven'],
  },

  // Preta-Work (Spirit Communication)
  {
    slug: 'preta-samvada',
    title: 'Preta-Samvada - Spirit Communication',
    sanskrit: 'प्रेत संवाद',
    category: 'preta-work',
    difficulty: 'advanced',
    description: 'Ritual dialogue with ancestral or unresolved spirits. Requires proper protocols and protection.',
    duration: 60,
    benefits: ['ancestral healing', 'resolution', 'liberation of spirits'],
    warnings: ['requires guru guidance', 'only during Krishna Paksha', 'ethical intent mandatory'],
    bestTithi: [8, 14, 29, 30],
  },
  {
    slug: 'preta-shuddhi',
    title: 'Preta Shuddhi - Spirit Purification',
    sanskrit: 'प्रेत शुद्धि',
    category: 'preta-work',
    difficulty: 'advanced',
    description: 'Rituals to purify and liberate stuck spirits. Includes mantra, yantra, and havan.',
    duration: 90,
    benefits: ['spirit liberation', 'karmic resolution', 'blessings'],
    warnings: ['powerful work', 'requires experience'],
  },

  // Additional practices to reach 55+
  {
    slug: 'mantra-pranava',
    title: 'Pranava Japa - Om Mantra',
    sanskrit: 'प्रणव जप',
    category: 'mantra',
    difficulty: 'beginner',
    description: 'Continuous recitation of Om (ॐ). Foundational practice.',
    duration: 30,
    benefits: ['liberation', 'cosmic connection', 'peace'],
  },
  {
    slug: 'mantra-gayatri',
    title: 'Gayatri Mantra',
    sanskrit: 'गायत्री मंत्र',
    category: 'mantra',
    difficulty: 'beginner',
    description: 'Vedic mantra to the Sun. Illumination of intellect.',
    duration: 15,
    benefits: ['wisdom', 'clarity', 'protection', 'divine grace'],
    bestTithi: [1, 6, 11],
  },
  {
    slug: 'meditation-so-ham',
    title: 'So\'ham Meditation',
    sanskrit: 'सोऽहं',
    category: 'vedanta',
    difficulty: 'beginner',
    description: 'I am That. Meditation on identity with Brahman through natural breath.',
    duration: 30,
    benefits: ['self-realization', 'peace', 'liberation', 'non-duality'],
  },
  {
    slug: 'meditation-yoga-nidra',
    title: 'Yoga Nidra - Yogic Sleep',
    sanskrit: 'योग निद्रा',
    category: 'vedanta',
    difficulty: 'beginner',
    description: 'Conscious sleep between waking and dreaming. Guided body scan and sankalpa.',
    duration: 45,
    benefits: ['deep rest', 'subconscious programming', 'healing', 'samadhi prep'],
  },
  {
    slug: 'ritual-agnihotra',
    title: 'Agnihotra - Fire Ritual',
    sanskrit: 'अग्निहोत्र',
    category: 'ritual',
    difficulty: 'intermediate',
    description: 'Daily offering to sacred fire at sunrise and sunset.',
    duration: 20,
    benefits: ['purification', 'atmospheric harmony', 'prosperity'],
  },
];
